name: Core debug build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag'
        required: true
        default: '2.20.1'
jobs:
  build-debug:
    name: Core debug build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'tiledb-inc/TileDB'
          ref: ${{ inputs.ref }}
      - uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: 3.22.1
      - name: Build (debug)
        run: |
          cmake \
            -DTILEDB_VERBOSE=ON \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
            -DCMAKE_C_COMPILER=/usr/bin/cc \
            -DCMAKE_TOOLCHAIN_FILE= \
            '-GUnix Makefiles' \
            .
