# This is a reusable workflow
# (https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow),
# called by python-ci-full.yml and python-ci-minimal.yml.

name: TileDB-SOMA Python CI

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      os:
        required: true
        type: string
      cc:
        required: false
        type: string
      cxx:
        required: false
        type: string
      report_codecov:
        required: true
        type: boolean
      run_lint:
        required: false
        type: boolean
        default: false

jobs:
  lint:
    if: inputs.run_lint
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout TileDB-SOMA
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Restore pre-commit cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ inputs.os }}-${{ inputs.python_version }}-${{ hashFiles('.github/workflows/python-ci-single.yml', '.pre-commit-config.yaml') }}

    - name: Install pre-commit
      run: pip -v install pre-commit

    - name: Log pip dependencies
      run: pip list

    - run: node --version
    - run: npm --version
    - name: Run pre-commit hooks on all files
      run: pre-commit run -a -v
