# This is a reusable workflow
# (https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow),
# called by python-ci-full.yml and python-ci-minimal.yml.

name: TileDB-SOMA Python CI

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      os:
        required: true
        type: string
      cc:
        required: false
        type: string
      cxx:
        required: false
        type: string
      report_codecov:
        required: true
        type: boolean
      run_lint:
        required: false
        type: boolean
        default: false

jobs:
  lint:
    if: inputs.run_lint
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout TileDB-SOMA
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Log pip dependencies
      run: pip list

  build:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Show matrix OS
      run: echo "inputs.os:" ${{ inputs.os }}

    - name: Linux CPU info
      if: ${{ inputs.os == 'ubuntu-24.04' }}
      run: cat /proc/cpuinfo

    - name: MacOS CPU info
      if: ${{ inputs.os == 'macos-latest' }}
      run: sysctl -a | grep cpu
    - name: Select XCode version
      if: startsWith(inputs.os, 'macos')
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Checkout TileDB-SOMA
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ensure we get all tags to inform package version determination

    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
