# This is a reusable workflow
# (https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow),
# called by python-ci-full.yml and python-ci-minimal.yml.
name: TileDB-SOMA Python CI
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      os:
        required: true
        type: string
jobs:
  lint:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 23
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - run: pip -v install pre-commit
    - run: pip list
    - run: node --version
    - run: npm --version
    - run: pre-commit run -a -v
